<?php

namespace AppBundle\DataAccess\Orm;

use Doctrine\ORM\EntityRepository;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistRepository extends EntityRepository
{
}
