<?php

namespace AppBundle\DataAccess\Orm;

use AppBundle\DataAccess\Contract\Entities\User;
use AppBundle\DataAccess\Contract\Repositories\UserRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository
    extends EntityRepository
    implements UserRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function getUsers() {
        return $this->createQueryBuilder('u')
            ->where('u.roles NOT LIKE :role')
            ->setParameter('role', '%ROLE_SUPER_ADMIN%')
            ->getQuery()
            ->getResult();
    }

    /**
     * {@inheritdoc}
     */
    public function getUser($userId)
    {
        return $this->createQueryBuilder('u')
            ->where('u.roles NOT LIKE :role')
            ->setParameter('role', '%ROLE_SUPER_ADMIN%')
            ->andWhere('u.id = :user_id')
            ->setParameter('user_id', $userId)
            ->getQuery()
            ->getSingleResult();
    }
}
