parameters:
    entity.user: AppBundle\DataAccess\Contract\Entities\User

services:
    business.user.list:
        class: AppBundle\Business\UserList
        arguments:
            userListDataAccess: '@data_access.business.user_list'

    business.user.get:
        class: AppBundle\Business\GetUser
        arguments:
            getUserDataAccess: '@data_access.business.get_user'