language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

env:
  CODECLIMATE_REPO_TOKEN: 45dadc0bf946392609a519855018c4926e339508f92fa7c00955d055cc2477e7

install:
  - ./tools/glide install

script:
  - ./tools/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip

 notifications:
    slack: open-gtd:T5ekEQD8hv7PeJsCvQPvH0iw