language: go
go:
  - 1.7.x
  - 1.8.x
  - tip

install:
  - ./tools/glide install

script:
  - ./tools/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip