services:
    controller.user.index:
        class: AppBundle\Controller\UserIndexController
        arguments:
            userRepository: '@repository.user'
            container: '@service_container'