<?php

namespace AppBundle\Repository;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistRepository extends \Doctrine\ORM\EntityRepository
{
}
