<?php

namespace AppBundle\Repository;

/**
 * ContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContextRepository extends \Doctrine\ORM\EntityRepository
{
}
