parameters:
    # Assetic
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        sass:    ~
        compass: ~