api:
    resource: "@AppBundle/Resources/config/routing/Api/routing.yml"
    prefix:   /api/v1/

app_daefault:
    resource: "@AppBundle/View/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing/routing.yml"

fos_user:
    resource: "../Resources/config/routing/user.yml"

api_login_check:
    path: /api/v1/login_check