api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   /api

app_management:
    resource: "@AppBundle/Controller/Management"
    type:     annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"