api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "../Resources/config/routing/user.yml"

api_login_check:
    path: /api/login_check