api:
    resource: "@AppBundle/View/Controller/Api"
    type:     annotation
    prefix:   /api

app_daefault:
    resource: "@AppBundle/View/Controller"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing/routing.yml"

fos_user:
    resource: "../Resources/config/routing/user.yml"

api_login_check:
    path: /api/login_check