api.v1.users.user.index:
    path: /users
    defaults: { _controller: api.controller.user.index:run }
    methods: [GET]
    options:
        expose: true

api.v1.users.user.get:
    path: /users/{userId}
    defaults: { _controller: api.controller.user.get:run }
    methods: [GET]
    options:
        expose: true