security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: "/profile"

#registration:
#  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#  prefix: "/register"

resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: "/resetting"

change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: "/profile"
