default:
    path: /

users.user.index:
    path: /users/index
    defaults: { _controller: controller.user.index:run }
    methods: [GET]
    options:
        expose: true

users.user.edit:
    path: /users/edit
    defaults: { _controller: controller.user.edit:run }
    methods: [GET, POST]
    options:
        expose: true

users.user.show:
    path: /users/show
    defaults: { _controller: controller.user.show:run }
    methods: [GET]
    options:
        expose: true

users.user.delete:
    path: /users/delete
    defaults: { _controller: controller.user.delete:run }
    methods: [DELETE]
    options:
        expose: true

fos_user:
    resource: "../Resources/config/routing/user.yml"

api_login_check:
    path: /api/login_check