parameters:
    entity.user: AppBundle\DataAccess\Contract\Entities\User

services:
    metadata.user:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            entityName: '%entity.user%'

    repository.user:
        class: AppBundle\DataAccess\Orm\UserRepository
        arguments:
            em: '@doctrine.orm.entity_manager'
            class: '@metadata.user'