services:
    api.controller.user.index:
        class: AppBundle\View\Controller\Api\User\GetUsersController
        arguments:
            userRepository: '@business.user.list'
            container: '@service_container'

    api.controller.user.get:
        class: AppBundle\View\Controller\Api\User\GetUserController
        arguments:
            userRepository: '@business.user.get'
            container: '@service_container'